import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './(components)/Navbar';
import '../globals.css';
import { getCategories } from '@/sanity/sanity-utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NextCommerce',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategories();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar categories={categories} />
        {children}
      </body>
    </html>
  );
}
